### ISSUE TITLE
Discountinuously cached addresses warning.

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#213]
I think that for the moment in case of discontinuous address caching there is no way to know whether the address was discontinuously cached or not.

Which may case some issue.

For instance if I run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -e` and then `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -s 3465 -b 100 -f` and `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -s 3767 -b 100 -f` the result of the `transaction list mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -x -l -f 3465 -e 3867` won't include the block 3736 (which I can see if I run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -e` and `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -s 3465 -b 400 -f`).

Moreover if after I've discontinuously cached the address on two different intervals (like above where I have only intervals from 3465 to 3565 and from 3767 to 3867 scanned) I can run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh` and the caching will start from the block 3868 as if the previous scanning were continuous.

Since the user may forget to have done a discontinuous scanning previously, I think it may worth considering a warning in such a case.
There is of course no need to remember all the start and end hashes of all the cached intervals, since the `address cache` command is perfectly conscious when the discontinuous scanning is performed, for instance in case I run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -s 4065 -b 50 -f` there is the following line in the output:
```
Forcing to cache block heights as required. Last stored block was 3867, continuing from block 4065 on.
```
So it would be enough to store just an additional bit of information in the blocklocator.json file, recording whether the scanning was discontinuous or not and to output a warning in case it was, both for the `address cache` as for the `transaction list` command if run with the `-l` flag.

What do you think?

**Comment by d5000** [comment]
I'm thinking about it, taking into account the use cases for discontinuous caching.

I think the main use case are addresses where the user knows they were created at a certain date. These would be cached from a block near this date. P2TH addresses are an even clearer example, here we know exactly when they were created - at the deck spawn transaction. So we don't need to cache them from block 0.

This use case would only seldom lead to situations where a warning would be appropiate. So my opinion is that in this case the user should be warned when he intends to cache the address with a different start block, but not when he uses the commands like `transaction list`. He should only be informed decently about the starting block, just like the other info which is displayed during many commands.

If the user however tries to "calculate" when he used the address, e.g. if it's a cold storage address, and caches discontiuously because of this, then this is more prone to errors and thus in this case there should be a warning also during operation.

So perhaps the best solution for the entries in blocklocator.json, without clogging the file too much, could be:

1) add a "start" parameter to all addresses where the caching started at a higher block height than 0, with the block height where caching started. The "start" parameter, when available, should always be shown in commands like `transaction list` or `address cache -v` (excluding `-q` options).

2) add a boolean "discontinuous" parameter to the address entries in where there are gaps between the caching phases. This one should trigger a stronger warning, so the user knows the data may be wrong if he messed up his caching.

That's my take on this issue for now, it would not require much time. The blocklocator.json's created during testing of course afterwards would have to be recreated. I guess this would be even more what you requested ;)

**Comment by buhtignew** [comment]
Indeed :-)

**Comment by d5000** [comment]
Implemented with the commits up to f88d247.

The warnings are still not perfect and I may still optimize them. But you're basically warned when trying to set a custom start block when caching, when caching discontinuously, and when using a blocklocator-based command with an address  which was cached discontinuously.

I also removed all confirmation dialogs for locator commands. In all cases where you could cache discontinuously you have to use the `-f` option.

blocklocator.json must be deleted, or all addresses where either a custom start block was set or discontinuously cached must be removed.

**Comment by buhtignew** [comment]
Like in the OP I've run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -e` and then `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -s 3465 -b 100 -f` and have seen a very clear warning.

Afterwards I've run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -s 3767 -b 100 -f` and have seen the following lines, which I considered a kind of warning to improve as mentioned in your previous post:
```
Forcing to cache block heights as required. The last commonly stored block was 3565, continuing from block 3767 on.
Addresses with gaps between cached blockheights will be marked as discontinuously cached.
```
However when I've run `transaction list mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -x -l -f 3465 -e 3867` there was no warning at all although, as mentioned in the OP, because of the discontinuous caching there was the block 3736 missing in the output.

Then I've run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh` and the caching has continued without any warning as well.

I've tried the same commands after I've deleted the `blocklocator.json` file and got the same results.

**Comment by d5000** [comment]
> However when I've run transaction list mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -x -l -f 3465 -e 3867 there was no warning at all although, as mentioned in the OP, because of the discontinuous caching, the block 3736 was missing in the output.

Yes, but a warning is not needed in this case: currently the behaviour is that if you use `transaction list` you can only cache the addresses if caching is done continuously, otherwise it will only show the transactions between the `-f` and `-e` block. So there is nothing stored in blocklocator.json when you use the command in this way, and thus there is also no warning.

I see no reason to change that: discontinuous caching should only be done with the `address cache` command, so the user never does it accidentally. Thus also it requires the `-f` option. If the user uses an option called `force`, he should be knowing what he's doing, so a more "intense" warning should not be necessary (if he doesn't use `-f` he will see a red warning and the command is aborted).

I have made a slight change to make that clearer: With the `--debug` option in this case (when the user tries to cache with `transaction list` discontinuously) a message was already displayed informing the user that nothing will be cached. I have changed it in a way it is always displayed if `-q` / `--quiet` is not used.

> I've also noticed that the discontinuous caching is mentioned in the address cache ADDRESS -v output (in case of address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -v for instance), but the fact that the caching has begun from a block different from 0 is not.

Strange, because normally you should see the following line in the `-v` output:

`First checked block height: X` ( X= block height)

**Comment by d5000** [comment]
> Since the output can be quite long so the user may never look into the first lines of the output, would it make sense/be possible to output this warning after the list of transactions were displayed?

This would be quite complicated due to the command structure. I have done the opposite now: I've moved the warnings to the start so the user sees them almost without delay (only in the case of deck cachings the delay is a bit longer). This is also imo better because so the user can decide if he wants to interrupt the command to take action or not, e.g. if he made a mistake when he cached an address discontinuously.

I have added a message now also to the situation you described in the second part of your post, i.e. the start block is always shown (exception: quiet option) in `transaction list -x -l` and `address cache` and `deck/token cache`. It's not a full-scale warning because as I wrote in an earlier post, an user who used `address cache -s -f` should know what he does and not be bothered with too intrusive warnings.

I also added a new option to `address cache` : `-v -a`. It will show all addresses in blocklocator.json and their data like if you use only `-v` for a list of addresses. I needed this for debugging but it is probably also useful for normal users.

A third change: if the user re-caches an address which was marked as "discontinuous" completely, from 0 on, then he will be allowed to do so and the discontinuous warning will disappear.

Commit a6ccdb9

**Comment by buhtignew** [comment]
>  I have done the opposite now: I've moved the warnings to the start so the user sees them almost without delay.

I think this can work, but since the transactions are already cached the time between the warning message output and the list transaction output is so short that it's impossible to notice the message.
(For example I've just run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -e -f`, `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -s 3465 -b 100 -f`, `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -s 3767 -b 100 -f` and `transaction list mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh -x -l -f 3465 -e 3867` to test the times.)
Thus the user will have to remember to look in the beginning of the output to see whether there is any warning there, which is basically the same as to remembering to have done discontinuous caching in the past.
Maybe we should introduce an artificial delay after the warning and before the list of transactions output in order the user be able to notice it.

We have the same situation in case the `address cache` was run from the block produced later than the `transaction list` range starts from. Although the message is less strong for the reasons you've mentioned we may consider trying to let the user seeing it.

By the way it seems like there is no way to run `address cache` from the block 0 at the moment.
For instance I've run `address cache mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP -e -f' and then `address cache mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP -s 0 -b 1000 -f` and got:
```
Storing blockheight locators for addresses: ['mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP']
Forced to re-cache adddress(es) from the first block on.

        General error raised by PeerAssets. Check if your input is correct.
```
I've run `transaction list mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP -x -l -f 0 -e 999` then I've got:
```
Searching transactions (this can take several minutes) ...
Starting at block: 0
Ending at block: 999
Processing block: 500
Stored block data until block 999 with hash 309a75eaed96bc4658b3b9a1e0c4cf453c752453b5aff572cb0d3a439e8631e0
No matching transactions found.
```
(The relevant line is `Processing block: 500` here.)
So the ` address cache` command hasn't processed blocks.

I've also tried `address cache mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP -e -f`, `address cache mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP  -b 1000 -f` and `transaction list mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP -x -l -f 0 -e 999` and got the same results.

> I also added a new option to `address cache -v -a`

This works and probably can be useful.

> f the user re-caches an address which was marked as "discontinuous" completely, from 0 on, then he will be allowed to do so if he uses address cache ADDRESS -s 0 -f and the discontinuous warning will disappear.

I was not able to test this feature because of the issue mentioned above.

**Comment by d5000** [comment]
I will not add an artificial delay to the messages. They are not that important to make the experience worse for users who know what they are doing. Again, they have used `--force` so they should, normally. 

> We have the same situation as in the previous section in case the address cache was run from the block produced later than the transaction list range starts from. Although the message is less strong for the reasons you've mentioned we may consider trying to let the user seeing it.

I get the message when I enter the commands as you wrote in the last post. The message is:

`Note: Address mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP was cached from the block height 22002 on.`

The `-s 0 -f` option is meant to replace the entry completely. The behaviour you discovered was a bug, which is fixed now.

**Comment by buhtignew** [comment]
> The behaviour you discovered was a bug, which is fixed now.
The behavior described [from here on](https://github.com/slimcoin-project/pacli/issues/213#moreover) still persists on my end.

**Comment by d5000** [comment]
While what you did here will almost never happen in the wild (why should you try to "re-cache" an address you just deleted?) I catched the error so it will in this case be just cached normally.

Commit: 4453b60

**Comment by buhtignew** [comment]
All is fine here, I'm closing.
